### ISSUE TITLE
"Getting started" not working

### ISSUE THREAD

**Issue by zopyx** [transpect/docx2hub#21]
I followed the instructions on the getting-start page.

The first Calabash example fails:

```
 ./calabash/calabash.sh -o result=MyXMLfile.xml docx2hub/xpl/docx2hub.xpl docx=MyWordfile.docx

Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/DataSource
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3308)
	at java.base/java.lang.Class.getMethod0(Class.java:3294)
	at java.base/java.lang.Class.getMethod(Class.java:2107)
	at com.xmlcalabash.core.XProcRuntime.initializeSteps(XProcRuntime.java:347)
	at com.xmlcalabash.core.XProcRuntime.<init>(XProcRuntime.java:296)
	at com.xmlcalabash.drivers.Main.run(Main.java:100)
	at com.xmlcalabash.drivers.Main.main(Main.java:83)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 9 more

```

```
 ls -la
total 36
drwx------   7 ajung ajung  4096 Nov 29 16:44 .
drwx------ 155 ajung ajung 12288 Nov 29 16:43 ..
drwx------  10 ajung ajung  4096 Nov 29 16:43 calabash
drwx------   8 ajung ajung  4096 Nov 29 16:44 docx2hub
drwx------   9 ajung ajung  4096 Nov 29 16:44 htmlreports
drwx------   2 ajung ajung  4096 Nov 29 16:44 xmlcatalog
drwx------  27 ajung ajung  4096 Nov 29 16:44 xslt-util

```

**Comment by mkraetke** [comment]
The issue with `javax.activation-api` should be resolved in the current version of the calabash-frontend.
